[package]
name = "bleps-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
litrs = "0.2.3"
syn = { version = "1.0.99", features = ["full"] }
uuid = "1.1.2"

[dev-dependencies]
bleps = { path = "../bleps" }
