[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
serialport = "4.2.0"
embedded-io = { version = "0.3.1", features = ["std"] }
bleps = { path = "../bleps" }
bleps-macros = { path = "../bleps-macros" }
env_logger = "0.10.0"
